version: 2.1
orbs:
  slack: circleci/slack@4.1
jobs:
  build:
    working_directory: ~/pro-1
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - slack/notify:
          channel: 'devops'
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
      - restore_cache:
          key: pro-1-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: pro-1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI  
      - run: xvfb-run -a npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

